[build-system]
requires = [
    "numpy>=1.0.0",
    "scipy>=1.0.0",
    "setuptools>=42",
    "setuptools_scm[toml]>=6.0"
    ]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "dirty-tag"
write_to = 'sht/_version.py'